Session-13/HRIS/HRIS.Web/Models/EmployeeLeaveModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRIS.Web.Models
{
    public class EmployeeLeaveModel : IModel<Guid>
    {
        [Key]
        public Guid Id { get; set; }
        public string? EmployeeId { get; set; }
        [Required]
        [Display(Name = "LeaveTypeModel")]
        public Guid LeaveTypeId { get; set; }
        [ForeignKey("LeaveTypeId")]
        [ValidateNever]
        public LeaveTypeModel LeaveTypeModel { get; set; }
        public DateTime LeaveDate { get; set; }
        public string? Remarks { get; set; }
    }
}

Session-13/HRIS/HRIS.Web/Models/ErrorViewModel.cs
namespace HRIS.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Session-13/HRIS/HRIS.Web/Models/IModel.cs
namespace HRIS.Web.Models
{
    public interface IModel<T>
    {
        T Id { get; set; }
    }
}

Session-13/HRIS/HRIS.Web/Models/LeaveTypeModel.cs
using System.ComponentModel.DataAnnotations;

namespace HRIS.Web.Models
{
    public class LeaveTypeModel : IModel<Guid>
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        public string? Title { get; set; }
    }
}

Session-13/HRIS/HRIS.Web/Controllers/EmployeeLeaveController.cs
using HRIS.Web.Models;
using HRIS.Web.Repository;
using Microsoft.AspNetCore.Mvc;

namespace HRIS.Web.Controllers
{
    public class EmployeeLeaveController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeLeaveController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmployeeLeaveModel obj)
        {
            obj.Id = Guid.NewGuid();

            if (ModelState.IsValid)
            {
                _unitOfWork.EmployeeLeave.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Create");
            }

            return View(obj);
        }


        [HttpGet]
        public ActionResult GetAll()
        {
            IEnumerable<EmployeeLeaveModel> objEmployeeLeaveList = _unitOfWork.EmployeeLeave.GetAll();
            return Json(new { data = objEmployeeLeaveList });
        }
    }
}

Session-13/HRIS/HRIS.Web/Controllers/EmployeeProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using System.Data;

namespace HRIS.Web.Controllers
{
    public class EmployeeProfileController : Controller
    {
        private readonly string _connectionString;
        private SqlConnection _sqlConnection;

        public EmployeeProfileController(IConfiguration config)
        {
            _connectionString = config.GetConnectionString("DefaultConnection");
            _sqlConnection = new SqlConnection(_connectionString);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetEmployeeProfileData()
        {
            _sqlConnection.Open();
            SqlCommand command = new SqlCommand("Select * from Hrms_Company_Employee_Profile", _sqlConnection);
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(command);
            DataSet ds = new DataSet();
            sqlDataAdapter.Fill(ds);
            var data1 = ds;
            //var data = from value in _unitOfWork.LeaveType.GetAll() select new { value.Id, value.Title };
            List<SelectListItem> employeeProfileList = new List<SelectListItem>();

            foreach(DataRow dr in ds.Tables[0].Rows)
            {
                employeeProfileList.Add(new SelectListItem { Text = dr["EmployeeName"].ToString(), Value = dr["EmployeeProfileId"].ToString() }); ;
            }

            var data = from value in employeeProfileList select new { value.Text, value.Value };

            _sqlConnection.Dispose();
            command.Dispose();
            ds.Dispose();

            return Json(data);
        }
    }
}

Session-13/HRIS/HRIS.Web/Controllers/HomeController.cs
using HRIS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HRIS.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Session-13/HRIS/HRIS.Web/Controllers/LeaveTypeController.cs
using HRIS.Web.Models;
using HRIS.Web.Repository;
using Microsoft.AspNetCore.Mvc;

namespace HRIS.Web.Controllers
{
    public class LeaveTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public LeaveTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LeaveTypeModel obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.LeaveType.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Create");
            }

            return View(obj);
        }

        [HttpGet]
        public JsonResult GetAll()
        {
            IEnumerable<LeaveTypeModel> objCoverTypeList = _unitOfWork.LeaveType.GetAll();
            return Json(new { data = objCoverTypeList });
        }

        [HttpGet]
        public ActionResult GetData()
        {
            var data = from value in _unitOfWork.LeaveType.GetAll() select new { value.Id, value.Title };
            return Json(data.ToList());
        }
    }
}

Session-13/HRIS/HRIS.Web/Views/EmployeeLeave/Create.cshtml
@model EmployeeLeaveModel


@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1 class="form-title"> Add Employee Leave</h1>
</div>

<form class="mt-5 mt-5" asp-antiforgery="true" asp-action="Create" asp-controller="EmployeeLeave" runat="server">
    <div class="mx-auto text-center mb-5" style="width: 620px;">

        <div class="form-group">
            <label asp-for="EmployeeId">Please select the employee</label>
            <select class="form-control" onchange="getEmployeeValue()" asp-for="EmployeeId" id="EmployeeProfileDropdown"></select>
            <span asp-validation-for="EmployeeId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LeaveTypeId">Please select the leave type</label>
            <select class="form-control" onchange="getValue()" asp-for="LeaveTypeId" id="LeaveTypeDropdown"></select>
            <span asp-validation-for="LeaveTypeId" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="LeaveDate"></label>
            <input type="datetime-local" class="form-control" asp-for="LeaveDate" class="form-control" />
            <span asp-validation-for="LeaveDate" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="Remarks"></label>
            <input type="text" asp-for="Remarks" class="form-control" />
            <span asp-validation-for="Remarks" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
    </div>>


</form>


<br /><br />

<table id="tblEmployeeLeaveData" class="table table-bordered table-striped" style="width: 100%">
    <thead>
        <tr>
            <th>Date</th>
            <th>Remarks</th>
        </tr>
    </thead>

        
</table>

@section Scripts 
{
    @{
        <partial name="_ValidationScriptsPartial" />

    }

    <script src="~/js/employeeProfile.js"></script>
    <script src="~/js/employeeLeave.js"></script>
    
}

Session-13/HRIS/HRIS.Web/Views/EmployeeLeave/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Session-13/HRIS/HRIS.Web/Views/LeaveType/Create.cshtml
@model LeaveTypeModel

@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1 class="form-title"> Add Leave Type</h1>
</div>

<form class="mt-5 mt-5" asp-antiforgery="true" asp-action="Create" asp-controller="LeaveType" method="post">
    <div class="mx-auto text-center mb-5" style="width: 620px;">
        <div class="form-group row">
            <label asp-for="Title"></label>
            <input type="text" class="form-control" asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
    </div>>
</form>

<br /><br /><br /><br />

<table id="tblData" class="table table-bordered table-striped" style="width: 100%">
    <thead>
        <tr>
            <th>Title</th>
            <th></th>
        </tr>
    </thead>

        
</table>


@section Scripts 
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script src="~/js/leaveType.js"></script>

}

Session-13/HRIS/HRIS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRIS.Web</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap-4.6.2-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HRIS.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
		    <div class="p-4 pt-5">
			    <h1 class="text-center"><a href="#" class="logo">HRIS</a></h1>
			    <ul class="list-unstyled components mb-5">
				    <li>
					    <a href="#">Company Information Form</a>
				    </li>
				    <li>
					    <a href="#">Company Division Form</a>
				    </li>
                    <li>
						<a href="#">Company Department Form</a>
					</li>
					<li>
						<a href="#">Company Section Form</a>
					</li>
                    <li>
						<a href="#">Company Designation Form</a>
					</li>
                    <li>
						<a href="#">Company Profile Form</a>
					</li>
                    <li>
						<a asp-controller="LeaveType" asp-action="Create">Leave Type Form</a>
					</li>
                    <li>
						<a asp-controller="EmployeeLeave" asp-action="Create">Employee Leave Form</a>
					</li>
			    </ul>
		    </div>
        </nav>

        <div id="content">
            @RenderBody()
        </div>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap-4.6.2-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


@*<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HRIS.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                    
            </div>
        </div>
    </nav>
</header>*@
@*<div class="container">
    <main role="main" class="pb-3">
            
    </main>
</div>*@