Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Models/AttendanceCreateModel.cs
using Autofac;
using EmployeeAttendance.Infrastructure.BusinessObjects;
using EmployeeAttendance.Infrastructure.Services;
using System.ComponentModel.DataAnnotations;

namespace EmployeeAttendance.Web.Areas.Admin.Models
{
    public class AttendanceCreateModel
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        public Guid EmployeeId { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
        [Required]
        public DateTime InTime { get; set; }
        [Required]
        public DateTime OutTime { get; set; }
        public string Remarks { get; set; }
        private ILifetimeScope _scope;
        private IAttendanceService _attendanceService;

        public AttendanceCreateModel()
        {

        }

        public AttendanceCreateModel(IAttendanceService attendanceService)
        {
            _attendanceService = attendanceService;
        }

        public void ResolveDependency(ILifetimeScope scope)
        {
            _scope = scope;
            _attendanceService = _scope.Resolve<IAttendanceService>();
        }

        internal void CreateAttendance()
        {
            Attendance attendance = new Attendance();

            attendance.EmployeeId = EmployeeId;
            attendance.CreatedDate = CreatedDate;
            attendance.InTime = InTime;
            attendance.OutTime = OutTime;
            attendance.Remarks = Remarks;

            _attendanceService.CreateAttendance(attendance);
        }

    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Models/AttendanceListModel.cs
using Autofac;
using EmployeeAttendance.Infrastructure.Services;

namespace EmployeeAttendance.Web.Areas.Admin.Models
{
    public class AttendanceListModel
    {
        private ILifetimeScope _scope;
        private IAttendanceService? _attendanceService;

        public AttendanceListModel(ILifetimeScope scope)
        {
            _scope = scope;
        }

        public void ResolveDependency(ILifetimeScope scope)
        {
            _scope = scope;
            _attendanceService = _scope.Resolve<IAttendanceService>();
        }

        internal object? GetAllAttendance()
        {
            return _attendanceService?.GetAllAtttendance();
        }

        internal object? GetAllModifiedAttendance()
        {
            return _attendanceService?.GetAllModifitedAttendance();
        }
    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Models/AttendanceViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeAttendance.Web.Areas.Admin.Models
{
    public class AttendanceViewModel
    {
        public AttendanceCreateModel Attendance { get; set; }
        [ValidateNever]
        public IEnumerable<SelectListItem> EmployeeList { get; set; }

        public AttendanceViewModel()
        {

        }
    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Models/EmployeeModel.cs
using Autofac;
using EmployeeAttendance.Infrastructure.Services;

namespace EmployeeAttendance.Web.Areas.Admin.Models
{
    public class EmployeeModel
    {
        private ILifetimeScope _scope;
        private IEmployeeService? _employeeService;

        public EmployeeModel()
        {

        }

        public void ResolveDependency(ILifetimeScope scope)
        {
            _scope = scope;
            _employeeService = _scope.Resolve<IEmployeeService>();
        }

        internal dynamic GetAllEmployeeProfile()
        {
            return _employeeService.GetAllEmployee();
        }
    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Models/ErrorViewModel.cs
namespace EmployeeAttendance.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Controllers/AttendanceController.cs
using Autofac;
using EmployeeAttendance.Infrastructure.DbContexts;
using EmployeeAttendance.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeAttendance.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AttendanceController : Controller
    {
        private readonly ILogger<AttendanceController> _logger;
        private readonly ILifetimeScope _scope;
        public AttendanceController(ILogger<AttendanceController> logger, ILifetimeScope scope)
        {
            _logger = logger;
            _scope = scope;
        }

        public IActionResult Index()
        {
            //_logger.LogInformation("I am in attendance index page");
            return RedirectToAction("Create");
        }

        public IActionResult Create()
        {
            AttendanceViewModel attendanceVM = _scope.Resolve<AttendanceViewModel>();
            attendanceVM.Attendance = _scope.Resolve<AttendanceCreateModel>();
            attendanceVM.EmployeeList = GetSelectedEmployeeProfileData();
            return View(attendanceVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AttendanceViewModel obj)
        {
            if (ModelState.IsValid)
            {
                _logger.LogInformation("Model State is valid during creating of attendance");
                obj.Attendance.ResolveDependency(_scope);

                try
                {
                    obj.Attendance.CreateAttendance();
                    TempData["success"] = "Attendance added successfully";
                    return RedirectToAction("Create");
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, ex.Message);
                    TempData["error"] = "Attendance didn't create successfully";
                }
            }
            else
            {
                TempData["error"] = "Attendance failed, due to incorrect inputs";
            }

            
            return View(obj);
        }

        [HttpGet]
        public ActionResult GetAllAttendance()
        {
            AttendanceListModel attendanceModel = _scope.Resolve<AttendanceListModel>();
            attendanceModel.ResolveDependency(_scope);

            var objAttendanceList = attendanceModel.GetAllAttendance();
            return Json(new { data = objAttendanceList });
        }

        [HttpGet]
        public ActionResult GetAllModifiedTimeAttendance()
        {
            AttendanceListModel attendanceModel = _scope.Resolve<AttendanceListModel>();
            attendanceModel.ResolveDependency(_scope);

            var objAttendanceModifiedList = attendanceModel.GetAllModifiedAttendance();
            return Json(new { data = objAttendanceModifiedList });
        }

        [HttpGet]
        public IEnumerable<SelectListItem> GetSelectedEmployeeProfileData()
        {
            EmployeeModel employeeModel = _scope.Resolve<EmployeeModel>();
            employeeModel.ResolveDependency(_scope);

            var data = employeeModel.GetAllEmployeeProfile();

            return data;
        }
    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Controllers/HomeController.cs
using EmployeeAttendance.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeAttendance.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Views/Attendance/Create.cshtml
@model AttendanceViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1 class="form-title">Add Employee Attendance</h1>
</div>


<form role="form" asp-antiforgery="true" asp-action="Create"
  asp-area="Admin" asp-controller="Attendance" method="post">
     <div class="mx-auto text-center mb-5" style="width: 620px;">
        <div class="form-group">
            <label asp-for="@Model.Attendance.EmployeeId">Please select the employee</label>
            <select class="form-control" asp-for="@Model.Attendance.EmployeeId" asp-items="@Model.EmployeeList">
                <option>Please select one</option>
            </select>
            <span asp-validation-for="@Model.Attendance.EmployeeId" class="text-danger"></span>
        </div>
    
        <div class="form-group row">
            <label asp-for="@Model.Attendance.CreatedDate"></label>
            <input type="date" asp-for="@Model.Attendance.CreatedDate" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
            <span asp-validation-for="@Model.Attendance.CreatedDate" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="@Model.Attendance.InTime"></label>
            <input type="time" asp-for="@Model.Attendance.InTime" class="form-control" value="@DateTime.Now.ToString("HH:mm")" />
            <span asp-validation-for="@Model.Attendance.InTime" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="@Model.Attendance.OutTime"></label>
            <input type="time" asp-for="@Model.Attendance.OutTime" class="form-control" />
            <span asp-validation-for="@Model.Attendance.OutTime" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <label asp-for="@Model.Attendance.Remarks"></label>
            <input type="text" asp-for="@Model.Attendance.Remarks" class="form-control" />
            <span asp-validation-for="@Model.Attendance.Remarks" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Create Attendance</button>
    </div>
</form> 


<br /><br />

<table id="tblAttendanceData" class="table table-bordered table-striped" style="width: 100%; text-align:center;">
    <thead>
        <tr>
            <th>EmployeeName</th>
            <th>CreatedDate</th>
            <th>InTime</th>
            <th>OutTime</th>
            <th>Remarks</th>
        </tr>
    </thead>

        
</table>


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/attendance.js"></script>
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRIS.Web</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap-4.6.2-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HRIS.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
		    <div class="p-4 pt-5">
			    <h1 class="text-center"><a href="#" class="logo">HRIS</a></h1>
			    <ul class="list-unstyled components mb-5">
				    <li>
					    <a asp-area="Admin" asp-controller="Attendance" asp-action="Create">Employee Attendance</a>
				    </li>
			    </ul>
		    </div>
        </nav>

        <div id="content">
            <partial name="_Notification" />
            @RenderBody()
        </div>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap-4.6.2-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Areas/Admin/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRIS.Web</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap-4.6.2-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HRIS.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
		    <div class="p-4 pt-5">
			    <h1 class="text-center"><a href="#" class="logo">HRIS</a></h1>
			    <ul class="list-unstyled components mb-5">
				    <li>
					    <a asp-area="Admin" asp-controller="Attendance" asp-action="Create">Employee Attendance</a>
				    </li>
			    </ul>
		    </div>
        </nav>

        <div id="content">
            <partial name="_Notification" />
            @RenderBody()
        </div>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap-4.6.2-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Final_hackathon/EmployeeAttendance/EmployeeAttendance.Web/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}